enyo.depends(
  "Count.js",
  "Filters.js",
  "Creator.js",
  "ClearCompleted.js",
  "Header.js",
  "List.js",
  "ToggleAll.js",
  "Footer.js",
  "Main.js",
  "App.js",
  "Row.js",
  "DestroyRow.js",
  "RowEditor.js",
  "FilterLink.js"
);